[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "oc4ids-datastore-api"
description = "OC4IDS Datastore API"
version = "0.1.0"
readme = "README.md"
dependencies = [
  "fastapi[standard]"
]
